define({
  root: ({
    useProxyTitle: "Use Proxy?",
    proxyPrefixTitle: "Address to Apply Prefix To",
    proxyAddressTitle: "Proxy Location",
    layerTitle: "Layer Name",
    layerType: "Layer Type",
    actions: "Actions",
    editdynamiclayer: "Edit Dynamic Layer",
    adddynamiclayer: "Add Dynamic Layer",
    addtiledlayer: "Add Tiled Layer",
    edittiledlayer: "Edit Tiled Layer",
    editfeaturelayer: "Edit Feature Layer",
    addfeaturelayer: "Add Feature Layer",
    editbasemaplayer: "Edit Basemap Layers",
    addbasemaplayer: "Add Basemap Layer",
    editbasemap: "Edit Basemap",
    addbasemap: "Add Basemap",
    cancel: "Cancel",
    ok: "OK",
    featurelayer: "Feature",
    dynamiclayer: "Dynamic",
    tiledlayer: "Tiled",
    basemaplayer: "Basemap",
    layerUrl: "Service URL",
    browse: "Browse",
    visibilityandtransparency: "Visibility / Transparency",
    transparency: "Transparency",
    imageFormat: "Image Format",
    imageDPI: "Image DPI",
    sublayers: "Sub-layers",
    basemaplayers: "Basemap Layers",
    autorefresh: "Auto refresh (minutes)",
    invaliddynamiclayer: "Invalid Dynamic Map Service URL",
    invalidfeaturelayer: "Invalid Feature Map Service URL",
    invalidBasemapUrl1: "This type of layer cannot be used as a basemap.",
    invalidBasemapUrl2: "Different spatial reference with current map.",
    invalidtiledlayer: "Invalid Tiled Map Service URL",
    popup: "Pop-up",
    featurelayermode: "Mode",
    modeondemand: "on-demand",
    modesnapshot: "snapshot",
    modeselection: "selection",
    displaylevels: "Display levels",
    isreferencelayer: "Reference Layer",
    addBaselayer: "Add Basemap Layer",
    configurepopup: "Configure Pop-up",
    removepopup: "Remove Pop-up",
    display: "Display",
    medias: "Medias",
    keyvalue: "Key Value",
    custom: "Custom",
    insertbold: "Insert Bold",
    insertitalic: "Insert Italic",
    insertunderline: "Insert Underline",
    inserthyperlink: "Insert Hyperlink",
    insertimage: "Insert Image",
    hyperlinkproperties: "Hyperlink Properties",
    uri: "URL",
    description: "Description",
    imageproperties: "Image Properties",
    disableclientcaching: "Disable Client Caching",
    reverseproxysettings: "Reverse Proxy Settings",
    showattachments: "Show Attachments"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "zh-cn": 0
});
