define({
  root: ({
    useProxyTitle: "Use Proxy?",
    proxyPrefixTitle: "Address to Apply Prefix To",
    proxyAddressTitle: "Proxy Location",
    layerTitle: "Layer Name",
    layerAlias: "Layer Alias",
    layerType: "Layer Type",
    actions: "Actions",
    reviewsettings: "Allow MapServer/FeatureServer Previews",
    editdynamiclayer: "Edit Dynamic Layer",
    adddynamiclayer: "Add Dynamic Layer",
    addtiledlayer: "Add Tiled Layer",
    edittiledlayer: "Edit Tiled Layer",
    editfeaturelayer: "Edit Feature Layer",
    addfeaturelayer: "Add Feature Layer",
    editbasemaplayer: "Edit Basemap Layers",
    addbasemaplayer: "Add Basemap Layer",
    addgeojsonlayer: "Add geoJSON Layer",
    addwebtilelayer: "Add WebTile Layer",
    addimagelayer: "Add Image Layer",
    addwmslayer: "Add WMS Layer",
    editgeojson: "Edit geoJSON Layer",
    editwebtile: "Edit WebTile Layer",
    editbasemap: "Edit Basemap",
    editimage: "Edit Image Layer",
    copyright: "Copyright Text",
    minScale: "Minimum Visibility Scale",
    maxScale: "Maximum Visibility Scale",
    labelMinScale: "Minimum Label Visibility",
    labelMaxScale: "Maximum Label Visibility",
    customLabel: "Custom Label Expression",
    customLabelStyle: "Custom Label Style",
    tilePlaceHolder: "e.g. http://{subDomain}.tile.stamen.com/watercolor/{level}/{col}/{row}.jpg",
    subDomainPlaceHolder: "e.g. a,b,c",
    displayLevelsPlaceHolder: "e.g 1,2,5",
    trackEditByLDAP: "Track Users When Editing (Windows AD)",
    limitEditByLDAP: "Only Allow Users to Edit Features They Created (Windows AD)",
    addbasemap: "Add Basemap",
    webmaplayertype: "Layer Type",
    layeroption: "Layer",
    basemapoption: "Basemap",
    cancel: "Cancel",
    visible: "Visible",
    queryable: "Queryable",
    showpopup: "Show Popup",
    ok: "OK",
    featurelayer: "Feature",
    dynamiclayer: "Dynamic",
    tiledlayer: "Tiled",
    basemaplayer: "Basemap",
    geojsonlayer: "geoJSON",
    imagelayer: "Image",
    wmslayer: "WMS",
    webtiledbasemap: "WebTile Basemap",
    webtiledlayer: "WebTile Layer",
    layerUrl: "Service URL",
    browse: "Browse",
    defQuery: "Definition Query",
    customRenderer: "Custom Renderer",
    visibilityandtransparency: "Visibility / Transparency",
    transparency: "Transparency",
    imageFormat: "Image Format",
    imageDPI: "Image DPI",
    sublayers: "Sub-layers",
    basemaplayers: "Basemap Layers",
    autorefresh: "Auto refresh (minutes)",
    hideinlegend: "Hide In Legend",
    invaliddynamiclayer: "Invalid Dynamic Map Service URL",
    invalidfeaturelayer: "Invalid Feature Map Service URL",
    invalidBasemapUrl1: "This type of layer cannot be used as a basemap.",
    invalidBasemapUrl2: "Different spatial reference with current map.",
    invalidtiledlayer: "Invalid Tiled Map Service URL",
    popup: "Pop-up",
    symbolpicker: "Pick Symbol",
    featurelayermode: "Mode",
    modeondemand: "on-demand",
    modesnapshot: "snapshot",
    modeselection: "selection",
    displaylevels: "Display levels",
    subdomains: "Subdomains",
    isreferencelayer: "Reference Layer",
    addBaselayer: "Add Basemap Layer",
    configuresymbol: "Configure Symbology",
    configurepopup: "Configure Pop-up",
    removepopup: "Remove Pop-up",
    display: "Display",
    medias: "Medias",
    keyvalue: "Key Value",
    custom: "Custom",
    insertbold: "Insert Bold",
    insertitalic: "Insert Italic",
    insertunderline: "Insert Underline",
    inserthyperlink: "Insert Hyperlink",
    insertimage: "Insert Image",
    hyperlinkproperties: "Hyperlink Properties",
    uri: "URL",
    description: "Description",
    imageproperties: "Image Properties",
    disableclientcaching: "Disable Client Caching",
    reverseproxysettings: "Reverse Proxy Settings",
    showattachments: "Show Attachments",
    format: "Format",
    edit: "Edit Field Format",
    decimalplaces0: "0 decimal places",
    decimalplaces1: "1 decimal places",
    decimalplaces2: "2 decimal places",
    decimalplaces3: "3 decimal places",
    decimalplaces4: "4 decimal places",
    decimalplaces5: "5 decimal places",
    decimalplaces6: "6 decimal places",
    latitudeField: "Latitude Field",
    longitudeField: "Longitude Field",
    featureArrayField: "Property Containing Array of Features",
    shortDate: "12/21/1997",
    shortDateLE: "21/12/1997",
    longMonthDayYear: "December 21,1997",
    dayShortMonthYear: "21 Dec 1997",
    longDate: "Sunday, December 21, 1997",
    shortDateLongTime: "12/21/1997 6:00:00 PM",
    shortDateLELongTime: "21/12/1997 6:00:00 PM",
    shortDateShortTime: "12/21/1997 6:00 PM",
    shortDateLEShortTime: "21/12/1997 6:00 PM",
    shortDateShortTime24: "12/21/1997 18:00",
    shortDateLEShortTime24: "21/12/1997 18:00",
    longMonthYear: "December 1997",
    shortMonthYear: "Dec 1997",
    year: "1997",
    usethousandssep: "Use 1000 separator",
    showLabels: "Show Labels?"
  }),
  "ar": 0,
  "cs": 0,
  "da": 0,
  "de": 0,
  "es": 0,
  "et": 0,
  "fi": 0,
  "fr": 0,
  "he": 0,
  "it": 0,
  "ja": 0,
  "ko": 0,
  "lt": 0,
  "lv": 0,
  "nb": 0,
  "nl": 0,
  "pl": 0,
  "pt-br": 0,
  "pt-pt": 0,
  "ro": 0,
  "ru": 0,
  "sv": 0,
  "th": 0,
  "tr": 0,
  "zh-cn": 0
});